project_name: aks-node-viewer
version: 2

before:
  hooks:
    - go mod download

builds:
  - binary: aks-node-viewer
    main: ./cmd/aks-node-viewer
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -v

universal_binaries:
  - replace: true

archives:
  - id: aks-node-viewer
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: binary

release:
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256_checksunms.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
