name: Release
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag to publish'
        type: string

jobs:
    prepare-variables:
        runs-on: ubuntu-latest
        outputs:
            release_tag:  ${{ steps.vars.outputs.release_tag }}
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
            with:
              egress-policy: audit
          - name: 'validate tag'
            id: vars
            run: |
                RELEASE_TAG=${{ inputs.releaseTag }}
                if [ -z "$RELEASE_TAG" ]; then
                    exit 1
                fi
                echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: prepare-variables
        steps:
        - name: Harden Runner
          uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
          with:
            egress-policy: audit
        - name: Checkout
          uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
          with:
            ref: ${{ needs.prepare-variables.outputs.release_tag }}
        - name: Set up Go
          uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
          with:
            go-version-file: go.mod
            check-latest: true
        - name: Print build tag
          run: echo "Building release ${{ needs.prepare-variables.outputs.release_tag }}"
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
          with:
            distribution: goreleaser
            version: latest
            args: release --clean
            workdir: .
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        